<?php 
# PAGE SETUP
include('../../src/setup.php');
# /PAGE SETUP
?>
<HTML STYLE="BACKGROUND-IMAGE:URL(MOTORBIKE.PNG)">
    <H1 COLOR=BLUE STYLE="COLOR:BLUE; BACKGROUND:BLACK">PAUL RICHARDSON INDUSTRIES PRESENTS</H1>
    <P STYLE="COLOR:BLUE; BACKGROUND:BLACK">THE COOLEST HOME PAGE</P>
    <H1>REVIEWS</H1>
    <P>I LOVE PAUL</P>
    <P>PAUL RICHARDSON IS THE COOLEST</P>
    <P>PAUL RICHARDSON IS THE BEST</P>
    <H1>TRUE FACTS!</H1>
    <P>I AM THE FASTEST AT RUNNING</P>
    <P>ONE TIME I JUMPED OFF THE ROOF OF THE SCHOOL AND IT WAS AWSOME AND EVERYONE THOUGHT I WOULD BE HURT BUT I DIDNT!!!!!</P>
    <H1>THE 3 AMIGOS</H1>
    <UL>
        <LI>BRYCE KILINJER</LI>
        <LI>ANDY LANDOWN</LI>
    </UL>
    <H1>COOL THINGS</H1>
    <UL>
        <LI>MOTORBIKES</LI>
        <LI>KNIFES</LI>
        <LI>VIDEO GAMES</LI>
        <LI>BOOKS</LI>
    </UL>
    <H1>BAD THINGS</H1>
    <UL>
        <LI>B</LI>
        <LI>WILLIAM PADILA</LI>
        <LI>KNIFES</LI>
    </UL>
<IMG SRC="PAULRICHARDSONDRAWING.PNG">
<IMG SRC="MOTORBIKE.PNG">
<BR>
<IMG SRC="MOTORBIKE.PNG">
<IMG SRC="AMERICA.GIF" STYLE="WIDTH:1000PX">
<P>BOO!</P>
</HTML>